### ISSUE TITLE
Allow _Tags_ and _All notes_ to be collapsed.

### ISSUE THREAD

**Issue by ryanpcmcquen** [standardnotes/titanium-theme#1]
This would actually be nice for all themes, but this one is my favourite, so this is where I would love to see it.

Adding in some kind of UI button that collapses everything but the text editor. This really allows you to focus on the text. Those two sidebars take a _lot_ of real estate on small screens!

**Comment by atmoio** [comment]
This is coming in 2.1 via resizable panels :)

**Comment by ryanpcmcquen** [comment]
@mobitar, will they be collapsible and resizable?

**Comment by atmoio** [comment]
Yup

On Jan 26, 2018, at 1:40 PM, Ryan P.C. McQuen <notifications@github.com>
wrote:

@mobitar <https://github.com/mobitar>, will they be collapsible and
resizable?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/sn-extensions/titanium-theme/issues/1#issuecomment-360884268>,
or mute the thread

**Comment by ryanpcmcquen** [comment]
Any ETA on that? I saw one of the betas was up a few months ago. :smile_cat:

**Comment by atmoio** [comment]
That was a _different_ 2.1 ;) That one was discarded altogether. This new 2.1 just commenced about a month ago. Getting close to completion.

**Comment by alandooz** [comment]
Maybe this one could be close with the resizable panels already implemented.
